// Auto-generated from MSFS24_World_Golf_Tour.xlsx
const TOUR_DATA = {
 "categories": [
  "GA / Light Jet",
  "Regional (ATR/ERJ)",
  "Narrowbody (A320/737)",
  "Widebody (A340/A350/777/MD-11)"
 ],
 "okField": {
  "GA / Light Jet": "gaOk",
  "Regional (ATR/ERJ)": "regionalOk",
  "Narrowbody (A320/737)": "narrowbodyOk",
  "Widebody (A340/A350/777/MD-11)": "widebodyOk"
 },
 "fleet": {
  "GA / Light Jet": {
   "planes": "Cirrus Vision Jet G2, Daher Kodiak 100, HondaJet, Citation X Winglets, + other GA aircraft",
   "speed": 200
  },
  "Regional (ATR/ERJ)": {
   "planes": "ATR 42-600, ATR 72-600, Embraer ERJ-190LR, Embraer ERJ-195LR",
   "speed": 270
  },
  "Narrowbody (A320/737)": {
   "planes": "A320, B737-600, B737-800, B737 MAX 8",
   "speed": 450
  },
  "Widebody (A340/A350/777/MD-11)": {
   "planes": "A340-300, A340-600, A350-900, A350-1000, B777-200, B777-300, MD-11",
   "speed": 480
  }
 },
 "thresholds": {
  "GA / Light Jet": {
   "min": null,
   "note": "No practical minimum in this route list (shortest strip used is 2,881 ft)"
  },
  "Regional (ATR/ERJ)": {
   "min": 4000,
   "note": "ft paved"
  },
  "Narrowbody (A320/737)": {
   "min": 5000,
   "note": "ft paved"
  },
  "Widebody (A340/A350/777/MD-11)": {
   "min": 9000,
   "note": "ft paved — raised to safely cover heavier variants like the 777-300ER"
  }
 },
 "courses": [
  {
   "id": 1,
   "played": false,
   "region": "Europe",
   "name": "Royal County Down",
   "country": "N. Ireland",
   "hub": "EGAA Belfast International Airport",
   "closer": null,
   "arrival": "EGAA",
   "runway": 9121,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 10",
   "majors": "Irish Open, Amateur Championship (no Open Championship yet)",
   "lat": 54.6575,
   "lon": -6.2158
  },
  {
   "id": 2,
   "played": false,
   "region": "Europe",
   "name": "Royal Portrush",
   "country": "N. Ireland",
   "hub": "EGAA Belfast International Airport",
   "closer": "EGAE City of Derry Airport",
   "arrival": "EGAE",
   "runway": 6460,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 20",
   "majors": "The Open Championship (2019, 1951, host of 2025)",
   "lat": 55.0428,
   "lon": -7.1611
  },
  {
   "id": 3,
   "played": false,
   "region": "Europe",
   "name": "Royal Birkdale",
   "country": "England",
   "hub": "EGCC Manchester Airport",
   "closer": null,
   "arrival": "EGCC",
   "runway": 10007,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 20",
   "majors": "The Open Championship (2017, 2008, 1998, 1991, 1983 etc.), Ryder Cup 1965 & 1969",
   "lat": 53.3494,
   "lon": -2.2795
  },
  {
   "id": 4,
   "played": false,
   "region": "Europe",
   "name": "Royal St George's",
   "country": "England",
   "hub": "EGKK London Gatwick Airport",
   "closer": null,
   "arrival": "EGKK",
   "runway": 10883,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 50",
   "majors": "The Open Championship (2021, 2011, 2003, 1993, 1985 etc.)",
   "lat": 51.1487,
   "lon": -0.1857
  },
  {
   "id": 5,
   "played": false,
   "region": "Europe",
   "name": "Sunningdale (Old)",
   "country": "England",
   "hub": "EGLL London Heathrow Airport",
   "closer": "EGLF Farnborough Airport",
   "arrival": "EGLF",
   "runway": 8005,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 100",
   "majors": "Walker Cup, Senior Open Championship, European Amateur",
   "lat": 51.2758,
   "lon": -0.7763
  },
  {
   "id": 6,
   "played": false,
   "region": "Europe",
   "name": "Wentworth (West)",
   "country": "England",
   "hub": "EGLL London Heathrow Airport",
   "closer": "EGLF Farnborough Airport",
   "arrival": "EGLF",
   "runway": 8005,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "World Top 100",
   "majors": "BMW PGA Championship (annual DP World Tour flagship), Ryder Cup 1953",
   "lat": 51.2758,
   "lon": -0.7763
  },
  {
   "id": 7,
   "played": false,
   "region": "Europe",
   "name": "Royal Dornoch",
   "country": "Scotland",
   "hub": "EGPE Inverness Airport",
   "closer": null,
   "arrival": "EGPE",
   "runway": 6194,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 20",
   "majors": "None (Amateur Championship, Scottish Boys)",
   "lat": 57.5425,
   "lon": -4.0475
  },
  {
   "id": 8,
   "played": false,
   "region": "Europe",
   "name": "Royal Troon",
   "country": "Scotland",
   "hub": "EGPF Glasgow Airport",
   "closer": null,
   "arrival": "EGPF",
   "runway": 8730,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 50",
   "majors": "The Open Championship (2016, 2004, 1997, 1989, 1982, 1973, host of 2028)",
   "lat": 55.8719,
   "lon": -4.4331
  },
  {
   "id": 9,
   "played": false,
   "region": "Europe",
   "name": "Turnberry (Ailsa)",
   "country": "Scotland",
   "hub": "EGPF Glasgow Airport",
   "closer": "EGPK Glasgow Prestwick Airport",
   "arrival": "EGPK",
   "runway": 9800,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 50",
   "majors": "The Open Championship (2009, 1994, 1986, 1977; off rota since 2021)",
   "lat": 55.5015,
   "lon": -4.5772
  },
  {
   "id": 10,
   "played": false,
   "region": "Europe",
   "name": "Muirfield",
   "country": "Scotland",
   "hub": "EGPH Edinburgh Airport",
   "closer": null,
   "arrival": "EGPH",
   "runway": 8392,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 20",
   "majors": "The Open Championship (2013, 2002, 1992, 1987, 1980, 1972, 1966)",
   "lat": 55.9501,
   "lon": -3.3723
  },
  {
   "id": 11,
   "played": false,
   "region": "Europe",
   "name": "St Andrews (Old Course)",
   "country": "Scotland",
   "hub": "EGPH Edinburgh Airport",
   "closer": "EGPN Dundee Airport",
   "arrival": "EGPN",
   "runway": 4593,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "Regional (ATR/ERJ)",
   "rating": 5,
   "ranking": "World Top 100 (frequently #1-5)",
   "majors": "The Open Championship (record 30+ times incl. 2022, host of 2027)",
   "lat": 56.4525,
   "lon": -3.0258
  },
  {
   "id": 12,
   "played": false,
   "region": "Europe",
   "name": "Carnoustie",
   "country": "Scotland",
   "hub": "EGPH Edinburgh Airport",
   "closer": "EGPN Dundee Airport",
   "arrival": "EGPN",
   "runway": 4593,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "Regional (ATR/ERJ)",
   "rating": 4.5,
   "ranking": "World Top 20",
   "majors": "The Open Championship (2018, 2007, 1999, 1975, 1968, 1953)",
   "lat": 56.4525,
   "lon": -3.0258
  },
  {
   "id": 13,
   "played": false,
   "region": "Europe",
   "name": "Kingsbarns",
   "country": "Scotland",
   "hub": "EGPH Edinburgh Airport",
   "closer": "EGPN Dundee Airport",
   "arrival": "EGPN",
   "runway": 4593,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "Regional (ATR/ERJ)",
   "rating": 4,
   "ranking": "World Top 100",
   "majors": "Scottish Open (co-host rotation, DP World Tour)",
   "lat": 56.4525,
   "lon": -3.0258
  },
  {
   "id": 14,
   "played": false,
   "region": "Europe",
   "name": "Waterville",
   "country": "Ireland",
   "hub": "EICK Cork International Airport",
   "closer": "EIKY Kerry Airport",
   "arrival": "EIKY",
   "runway": 6562,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "World Top 100",
   "majors": "None (traditional pre-Open warm-up course)",
   "lat": 52.1809,
   "lon": -9.5238
  },
  {
   "id": 15,
   "played": false,
   "region": "Europe",
   "name": "Portmarnock",
   "country": "Ireland",
   "hub": "EIDW Dublin Airport",
   "closer": null,
   "arrival": "EIDW",
   "runway": 10203,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 50",
   "majors": "Irish Open (multiple), Walker Cup 1991",
   "lat": 53.4287,
   "lon": -6.2621
  },
  {
   "id": 16,
   "played": false,
   "region": "Europe",
   "name": "Ballybunion",
   "country": "Ireland",
   "hub": "EINN Shannon Airport",
   "closer": null,
   "arrival": "EINN",
   "runway": 10495,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 50",
   "majors": "Irish Open (historic)",
   "lat": 52.702,
   "lon": -8.9248
  },
  {
   "id": 17,
   "played": false,
   "region": "Europe",
   "name": "Lahinch",
   "country": "Ireland",
   "hub": "EINN Shannon Airport",
   "closer": null,
   "arrival": "EINN",
   "runway": 10495,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "World Top 100",
   "majors": "Irish Open (2019 and historic editions)",
   "lat": 52.702,
   "lon": -8.9248
  },
  {
   "id": 18,
   "played": false,
   "region": "Europe",
   "name": "Falsterbo",
   "country": "Sweden",
   "hub": "EKCH Copenhagen Kastrup Airport",
   "closer": "ESMS Malmö Sturup Airport",
   "arrival": "ESMS",
   "runway": 9186,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "Sweden Top 10",
   "majors": "Scandinavian Masters (historic host)",
   "lat": 55.5356,
   "lon": 13.3763
  },
  {
   "id": 19,
   "played": false,
   "region": "Europe",
   "name": "Lofoten Links",
   "country": "Norway",
   "hub": "ENEV Harstad/Narvik Airport",
   "closer": "ENLK Leknes Airport",
   "arrival": "ENLK",
   "runway": 2881,
   "gaOk": true,
   "regionalOk": false,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "rating": 4.5,
   "ranking": "World Top 25 (#24, 2024-25)",
   "majors": "None (Arctic golf novelty)",
   "lat": 68.1525,
   "lon": 13.6094
  },
  {
   "id": 20,
   "played": false,
   "region": "Europe",
   "name": "Halmstad GK",
   "country": "Sweden",
   "hub": "ESGG Göteborg Landvetter Airport",
   "closer": "ESMT Halmstad Airport",
   "arrival": "ESMT",
   "runway": 7419,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "Sweden Top 10",
   "majors": "Scandinavian Masters (historic host)",
   "lat": 56.6911,
   "lon": 12.8202
  },
  {
   "id": 21,
   "played": false,
   "region": "Europe",
   "name": "Bro Hof Slott",
   "country": "Sweden",
   "hub": "ESSA Stockholm-Arlanda Airport",
   "closer": "ESSB Stockholm-Bromma Airport",
   "arrival": "ESSB",
   "runway": 5472,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "Sweden Top 5",
   "majors": "Nordea Masters / Scandinavian Masters (host years)",
   "lat": 59.3544,
   "lon": 17.9417
  },
  {
   "id": 22,
   "played": false,
   "region": "Europe",
   "name": "Visby",
   "country": "Sweden",
   "hub": "ESSA Stockholm-Arlanda Airport",
   "closer": "ESSV Visby Airport",
   "arrival": "ESSV",
   "runway": 6562,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 3,
   "ranking": "Regional favorite",
   "majors": "None",
   "lat": 57.6628,
   "lon": 18.3462
  },
  {
   "id": 23,
   "played": false,
   "region": "Europe",
   "name": "Camiral (PGA Catalunya)",
   "country": "Spain",
   "hub": "LEBL Josep Tarradellas Barcelona-El Prat Airport",
   "closer": "LEGE Girona-Costa Brava Airport",
   "arrival": "LEGE",
   "runway": 7874,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "Spain Top 10",
   "majors": "Spanish Open",
   "lat": 41.9046,
   "lon": 2.7618
  },
  {
   "id": 24,
   "played": false,
   "region": "Europe",
   "name": "Valderrama",
   "country": "Spain",
   "hub": "LEMG Málaga-Costa del Sol Airport",
   "closer": null,
   "arrival": "LEMG",
   "runway": 10500,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 50",
   "majors": "Ryder Cup 1997, Volvo Masters (many years)",
   "lat": 36.6749,
   "lon": -4.4991
  },
  {
   "id": 25,
   "played": false,
   "region": "Europe",
   "name": "Finca Cortesín",
   "country": "Spain",
   "hub": "LEMG Málaga-Costa del Sol Airport",
   "closer": null,
   "arrival": "LEMG",
   "runway": 10500,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 100",
   "majors": "Volvo World Match Play Championship",
   "lat": 36.6749,
   "lon": -4.4991
  },
  {
   "id": 26,
   "played": false,
   "region": "Europe",
   "name": "Real Club Sotogrande",
   "country": "Spain",
   "hub": "LEMG Málaga-Costa del Sol Airport",
   "closer": null,
   "arrival": "LEMG",
   "runway": 10500,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "Spain Top 10",
   "majors": "Spanish Open, Andalucía Masters",
   "lat": 36.6749,
   "lon": -4.4991
  },
  {
   "id": 27,
   "played": false,
   "region": "Europe",
   "name": "Marco Simone",
   "country": "Italy",
   "hub": "LIRF Rome–Fiumicino Leonardo da Vinci International Airport",
   "closer": null,
   "arrival": "LIRF",
   "runway": 12801,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "Italy #1",
   "majors": "Ryder Cup 2023",
   "lat": 41.8045,
   "lon": 12.252
  },
  {
   "id": 28,
   "played": false,
   "region": "Europe",
   "name": "Quinta do Lago",
   "country": "Portugal",
   "hub": "LPFR Faro - Gago Coutinho International Airport",
   "closer": null,
   "arrival": "LPFR",
   "runway": 8169,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "Portugal Top 5",
   "majors": "Portugal Masters",
   "lat": 37.0159,
   "lon": -7.9709
  },
  {
   "id": 29,
   "played": false,
   "region": "Europe",
   "name": "Monte Rei",
   "country": "Portugal",
   "hub": "LPFR Faro - Gago Coutinho International Airport",
   "closer": null,
   "arrival": "LPFR",
   "runway": 8169,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "Portugal #1",
   "majors": "None",
   "lat": 37.0159,
   "lon": -7.9709
  },
  {
   "id": 30,
   "played": false,
   "region": "Europe",
   "name": "Terras da Comporta",
   "country": "Portugal",
   "hub": "LPPT Lisbon Humberto Delgado Airport",
   "closer": null,
   "arrival": "LPPT",
   "runway": 12500,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "New/rising",
   "majors": "None",
   "lat": 38.7813,
   "lon": -9.1359
  },
  {
   "id": 31,
   "played": false,
   "region": "Africa",
   "name": "Arabella",
   "country": "South Africa",
   "hub": "FACT Cape Town International Airport",
   "closer": null,
   "arrival": "FACT",
   "runway": 10502,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "South Africa Top 10",
   "majors": "South African Open (historic)",
   "lat": -33.974,
   "lon": 18.6043
  },
  {
   "id": 32,
   "played": false,
   "region": "Africa",
   "name": "Fancourt (Links)",
   "country": "South Africa",
   "hub": "FACT Cape Town International Airport",
   "closer": "FAGG George Airport",
   "arrival": "FAGG",
   "runway": 6562,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "Africa Top 5",
   "majors": "Presidents Cup 2003",
   "lat": -34.0056,
   "lon": 22.3789
  },
  {
   "id": 33,
   "played": false,
   "region": "Africa",
   "name": "Leopard Creek",
   "country": "South Africa",
   "hub": "FAOR O.R. Tambo International Airport",
   "closer": "FANS Nelspruit Airport",
   "arrival": "FANS",
   "runway": 3419,
   "gaOk": true,
   "regionalOk": false,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "rating": 4.5,
   "ranking": "Africa #1-2",
   "majors": "Alfred Dunhill Championship",
   "lat": -25.5,
   "lon": 30.9138
  },
  {
   "id": 34,
   "played": false,
   "region": "Africa",
   "name": "Gary Player CC",
   "country": "South Africa",
   "hub": "FAOR O.R. Tambo International Airport",
   "closer": "FAPN Pilanesberg International Airport",
   "arrival": "FAPN",
   "runway": 9022,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "South Africa Top 10",
   "majors": "Nedbank Golf Challenge (annual)",
   "lat": -25.3338,
   "lon": 27.1734
  },
  {
   "id": 35,
   "played": false,
   "region": "Asia",
   "name": "Yas Links",
   "country": "UAE",
   "hub": "OMAA Zayed International Airport",
   "closer": null,
   "arrival": "OMAA",
   "runway": 13471,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "Middle East Top 5",
   "majors": "Abu Dhabi HSBC Championship (rotation host)",
   "lat": 24.441,
   "lon": 54.6492
  },
  {
   "id": 36,
   "played": false,
   "region": "Asia",
   "name": "Emirates GC",
   "country": "UAE",
   "hub": "OMDB Dubai International Airport",
   "closer": null,
   "arrival": "OMDB",
   "runway": 14590,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "Middle East #1",
   "majors": "Dubai Desert Classic",
   "lat": 25.2498,
   "lon": 55.371
  },
  {
   "id": 37,
   "played": false,
   "region": "Asia",
   "name": "Hirono",
   "country": "Japan",
   "hub": "RJBB Kansai International Airport",
   "closer": null,
   "arrival": "RJBB",
   "runway": 13123,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "Japan #1 / World Top 30",
   "majors": "Japan Open (occasional host)",
   "lat": 34.4273,
   "lon": 135.244
  },
  {
   "id": 38,
   "played": false,
   "region": "Asia",
   "name": "Kawana (Fuji Course)",
   "country": "Japan",
   "hub": "RJTT Tokyo Haneda International Airport",
   "closer": "RJTO Oshima Airport",
   "arrival": "RJTO",
   "runway": 5905,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "rating": 4.5,
   "ranking": "Japan Top 5",
   "majors": "None",
   "lat": 34.782,
   "lon": 139.36
  },
  {
   "id": 39,
   "played": false,
   "region": "Asia",
   "name": "Nine Bridges",
   "country": "South Korea",
   "hub": "RKSI Incheon International Airport",
   "closer": "RKPC Jeju International Airport",
   "arrival": "RKPC",
   "runway": 10433,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 100",
   "majors": "The CJ Cup (PGA Tour, 2017-2020)",
   "lat": 33.5121,
   "lon": 126.4925
  },
  {
   "id": 40,
   "played": false,
   "region": "Asia",
   "name": "Sentosa (Serapong)",
   "country": "Singapore",
   "hub": "WSSS Singapore Changi Airport",
   "closer": null,
   "arrival": "WSSS",
   "runway": 13123,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "Asia Top 10",
   "majors": "SMBC Singapore Open",
   "lat": 1.3502,
   "lon": 103.994
  },
  {
   "id": 41,
   "played": false,
   "region": "Asia",
   "name": "Mission Hills",
   "country": "China",
   "hub": "ZGSZ Shenzhen Bao'an International Airport",
   "closer": null,
   "arrival": "ZGSZ",
   "runway": 12467,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 3.5,
   "ranking": "World's largest golf club (Guinness)",
   "majors": "World Cup of Golf (historic host)",
   "lat": 22.6395,
   "lon": 113.8033
  },
  {
   "id": 42,
   "played": false,
   "region": "Oceania",
   "name": "Kauri Cliffs",
   "country": "New Zealand",
   "hub": "NZAA Auckland International Airport",
   "closer": "NZKK Kerikeri Airport",
   "arrival": "NZKK",
   "runway": 3904,
   "gaOk": true,
   "regionalOk": false,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "rating": 4.5,
   "ranking": "World Top 50",
   "majors": "None",
   "lat": -35.2591,
   "lon": 173.9133
  },
  {
   "id": 43,
   "played": false,
   "region": "Oceania",
   "name": "Cape Kidnappers",
   "country": "New Zealand",
   "hub": "NZAA Auckland International Airport",
   "closer": "NZNR Hawke's Bay Airport",
   "arrival": "NZNR",
   "runway": 5741,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 50",
   "majors": "None",
   "lat": -39.4658,
   "lon": 176.87
  },
  {
   "id": 44,
   "played": false,
   "region": "Oceania",
   "name": "Jack's Point",
   "country": "New Zealand",
   "hub": "NZQN Queenstown Airport",
   "closer": null,
   "arrival": "NZQN",
   "runway": 6204,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "NZ Top 10",
   "majors": "None",
   "lat": -45.0192,
   "lon": 168.7464
  },
  {
   "id": 45,
   "played": false,
   "region": "Oceania",
   "name": "Royal Melbourne (Composite)",
   "country": "Australia",
   "hub": "YMML Melbourne Airport",
   "closer": null,
   "arrival": "YMML",
   "runway": 11998,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 10",
   "majors": "Presidents Cup (1998, 2011, 2019), World Cup",
   "lat": -37.6707,
   "lon": 144.8379
  },
  {
   "id": 46,
   "played": false,
   "region": "Oceania",
   "name": "Kingston Heath",
   "country": "Australia",
   "hub": "YMML Melbourne Airport",
   "closer": null,
   "arrival": "YMML",
   "runway": 11998,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 30",
   "majors": "Australian Open, Australian Masters",
   "lat": -37.6707,
   "lon": 144.8379
  },
  {
   "id": 47,
   "played": false,
   "region": "Oceania",
   "name": "Barnbougle Dunes",
   "country": "Australia",
   "hub": "YMML Melbourne Airport",
   "closer": "YDPO Devonport Airport",
   "arrival": "YDPO",
   "runway": 6030,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 50",
   "majors": "None",
   "lat": -41.1697,
   "lon": 146.43
  },
  {
   "id": 48,
   "played": false,
   "region": "Oceania",
   "name": "Cape Wickham",
   "country": "Australia",
   "hub": "YMML Melbourne Airport",
   "closer": "YKII King Island Airport",
   "arrival": "YKII",
   "runway": 5198,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "rating": 4.5,
   "ranking": "World Top 50",
   "majors": "None",
   "lat": -39.8775,
   "lon": 143.878
  },
  {
   "id": 49,
   "played": false,
   "region": "Pacific",
   "name": "Kapalua (Plantation Course)",
   "country": "Hawaii",
   "hub": "PHNL Daniel K. Inouye International Airport",
   "closer": "PHOG Kahului International Airport",
   "arrival": "PHOG",
   "runway": 6998,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 100",
   "majors": "Sentry Tournament of Champions (PGA Tour season opener)",
   "lat": 20.8963,
   "lon": -156.4318
  },
  {
   "id": 50,
   "played": false,
   "region": "North America",
   "name": "Cabot Cliffs",
   "country": "Canada",
   "hub": "CYHZ Halifax / Stanfield International Airport",
   "closer": "CYQY Sydney / J.A. Douglas McCurdy Airport",
   "arrival": "CYQY",
   "runway": 7070,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 20",
   "majors": "None",
   "lat": 46.1611,
   "lon": -60.0498
  },
  {
   "id": 51,
   "played": false,
   "region": "North America",
   "name": "Cabot Links",
   "country": "Canada",
   "hub": "CYHZ Halifax / Stanfield International Airport",
   "closer": "CYQY Sydney / J.A. Douglas McCurdy Airport",
   "arrival": "CYQY",
   "runway": 7070,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "World Top 100",
   "majors": "None",
   "lat": 46.1611,
   "lon": -60.0498
  },
  {
   "id": 52,
   "played": false,
   "region": "North America",
   "name": "Augusta National",
   "country": "USA",
   "hub": "KATL Hartsfield Jackson Atlanta International Airport",
   "closer": "KAGS Augusta Regional At Bush Field",
   "arrival": "KAGS",
   "runway": 8001,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 3",
   "majors": "The Masters (annual)",
   "lat": 33.3699,
   "lon": -81.9645
  },
  {
   "id": 53,
   "played": false,
   "region": "North America",
   "name": "Kiawah Island (Ocean Course)",
   "country": "USA",
   "hub": "KCHS Charleston International Airport",
   "closer": null,
   "arrival": "KCHS",
   "runway": 9001,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 30",
   "majors": "PGA Championship (2021, 2012), Ryder Cup 1991",
   "lat": 32.8962,
   "lon": -80.0382
  },
  {
   "id": 54,
   "played": false,
   "region": "North America",
   "name": "Pinehurst No. 2",
   "country": "USA",
   "hub": "KCLT Charlotte Douglas International Airport",
   "closer": "KSOP Moore County Airport",
   "arrival": "KSOP",
   "runway": 6503,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 10",
   "majors": "U.S. Open (2024, 2014, 2005, 1999), Ryder Cup 1951",
   "lat": 35.2372,
   "lon": -79.3894
  },
  {
   "id": 55,
   "played": false,
   "region": "North America",
   "name": "Sand Hills",
   "country": "USA",
   "hub": "KDEN Denver International Airport",
   "closer": "KAIA Alliance Municipal Airport",
   "arrival": "KAIA",
   "runway": 9203,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 10",
   "majors": "None (private, remote)",
   "lat": 42.0525,
   "lon": -102.804
  },
  {
   "id": 56,
   "played": false,
   "region": "North America",
   "name": "TPC Sawgrass (Stadium)",
   "country": "USA",
   "hub": "KJAX Jacksonville International Airport",
   "closer": null,
   "arrival": "KJAX",
   "runway": 10000,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 50",
   "majors": "THE PLAYERS Championship (annual)",
   "lat": 30.4925,
   "lon": -81.6878
  },
  {
   "id": 57,
   "played": false,
   "region": "North America",
   "name": "Whistling Straits",
   "country": "USA",
   "hub": "KMKE General Mitchell International Airport",
   "closer": "KSBM Sheboygan County Memorial Airport",
   "arrival": "KSBM",
   "runway": 6801,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 30",
   "majors": "PGA Championship (2004, 2010, 2015), Ryder Cup 2021",
   "lat": 43.7696,
   "lon": -87.8514
  },
  {
   "id": 58,
   "played": false,
   "region": "North America",
   "name": "Bandon Dunes",
   "country": "USA",
   "hub": "KPDX Portland International Airport",
   "closer": "KOTH Southwest Oregon Regional Airport",
   "arrival": "KOTH",
   "runway": 5980,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 50",
   "majors": "U.S. Amateur 2020",
   "lat": 43.4171,
   "lon": -124.246
  },
  {
   "id": 59,
   "played": false,
   "region": "North America",
   "name": "Chambers Bay",
   "country": "USA",
   "hub": "KSEA Seattle–Tacoma International Airport",
   "closer": null,
   "arrival": "KSEA",
   "runway": 11901,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "World Top 100",
   "majors": "U.S. Open 2015",
   "lat": 47.4479,
   "lon": -122.3103
  },
  {
   "id": 60,
   "played": false,
   "region": "North America",
   "name": "Pebble Beach",
   "country": "USA",
   "hub": "KSFO San Francisco International Airport",
   "closer": "KMRY Monterey Regional Airport",
   "arrival": "KMRY",
   "runway": 7175,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 10",
   "majors": "U.S. Open (2019, 2010, 2000, 1992, 1982, 1972), AT&T Pro-Am (annual)",
   "lat": 36.5868,
   "lon": -121.8442
  },
  {
   "id": 61,
   "played": false,
   "region": "North America",
   "name": "Cypress Point",
   "country": "USA",
   "hub": "KSFO San Francisco International Airport",
   "closer": "KMRY Monterey Regional Airport",
   "arrival": "KMRY",
   "runway": 7175,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 5,
   "ranking": "World Top 3",
   "majors": "Bing Crosby Pro-Am (historic, precursor to AT&T)",
   "lat": 36.5868,
   "lon": -121.8442
  },
  {
   "id": 62,
   "played": false,
   "region": "North America",
   "name": "Spyglass Hill",
   "country": "USA",
   "hub": "KSFO San Francisco International Airport",
   "closer": "KMRY Monterey Regional Airport",
   "arrival": "KMRY",
   "runway": 7175,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4.5,
   "ranking": "World Top 100",
   "majors": "AT&T Pebble Beach Pro-Am (rotation course)",
   "lat": 36.5868,
   "lon": -121.8442
  },
  {
   "id": 63,
   "played": false,
   "region": "South America",
   "name": "Pilar Golf Club",
   "country": "Argentina",
   "hub": "SAEZ Ezeiza International Airport - Ministro Pistarini",
   "closer": null,
   "arrival": "SAEZ",
   "runway": 10827,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 3.5,
   "ranking": "Argentina Top 10",
   "majors": "None on record",
   "lat": -34.8222,
   "lon": -58.5358
  },
  {
   "id": 64,
   "played": false,
   "region": "South America",
   "name": "Chapelco",
   "country": "Argentina",
   "hub": "SAEZ Ezeiza International Airport - Ministro Pistarini",
   "closer": "SAZY Aviador C. Campos Airport",
   "arrival": "SAZY",
   "runway": 8205,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "rating": 4,
   "ranking": "Argentina Top 5",
   "majors": "None",
   "lat": -40.0754,
   "lon": -71.1373
  },
  {
   "id": 65,
   "played": false,
   "region": "South America",
   "name": "Olympic GC",
   "country": "Brazil",
   "hub": "SBGL Rio Galeão – Tom Jobim International Airport",
   "closer": null,
   "arrival": "SBGL",
   "runway": 13123,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 3.5,
   "ranking": "South America Top 5",
   "majors": "2016 Rio Olympics golf events",
   "lat": -22.81,
   "lon": -43.2506
  },
  {
   "id": 66,
   "played": false,
   "region": "South America",
   "name": "São Fernando GC",
   "country": "Brazil",
   "hub": "SBGR São Paulo/Guarulhos–Governor André Franco Montoro International Airport",
   "closer": null,
   "arrival": "SBGR",
   "runway": 12139,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "rating": 3,
   "ranking": "Regional favorite",
   "majors": "None on record",
   "lat": -23.4313,
   "lon": -46.47
  }
 ],
 "legs": [
  {
   "id": 1,
   "from": "EGAA",
   "fromName": "Belfast International Airport",
   "to": "EGAE",
   "toName": "City of Derry Airport",
   "fromLat": 54.6575,
   "fromLon": -6.2158,
   "toLat": 55.0428,
   "toLon": -7.1611,
   "distance": 40,
   "runway": 6460,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 05m"
  },
  {
   "id": 2,
   "from": "EGAE",
   "fromName": "City of Derry Airport",
   "to": "EGCC",
   "toName": "Manchester Airport",
   "fromLat": 55.0428,
   "fromLon": -7.1611,
   "toLat": 53.3494,
   "toLon": -2.2795,
   "distance": 199,
   "runway": 10007,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 27m"
  },
  {
   "id": 3,
   "from": "EGCC",
   "fromName": "Manchester Airport",
   "to": "EGKK",
   "toName": "London Gatwick Airport",
   "fromLat": 53.3494,
   "fromLon": -2.2795,
   "toLat": 51.1487,
   "toLon": -0.1857,
   "distance": 153,
   "runway": 10883,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 20m"
  },
  {
   "id": 4,
   "from": "EGKK",
   "fromName": "London Gatwick Airport",
   "to": "EGLF",
   "toName": "Farnborough Airport",
   "fromLat": 51.1487,
   "fromLon": -0.1857,
   "toLat": 51.2758,
   "toLon": -0.7763,
   "distance": 23,
   "runway": 8005,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 03m"
  },
  {
   "id": 5,
   "from": "EGLF",
   "fromName": "Farnborough Airport",
   "to": "EGPE",
   "toName": "Inverness Airport",
   "fromLat": 51.2758,
   "fromLon": -0.7763,
   "toLat": 57.5425,
   "toLon": -4.0475,
   "distance": 393,
   "runway": 6194,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 52m"
  },
  {
   "id": 6,
   "from": "EGPE",
   "fromName": "Inverness Airport",
   "to": "EGPF",
   "toName": "Glasgow Airport",
   "fromLat": 57.5425,
   "fromLon": -4.0475,
   "toLat": 55.8719,
   "toLon": -4.4331,
   "distance": 101,
   "runway": 8730,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 13m"
  },
  {
   "id": 7,
   "from": "EGPF",
   "fromName": "Glasgow Airport",
   "to": "EGPK",
   "toName": "Glasgow Prestwick Airport",
   "fromLat": 55.8719,
   "fromLon": -4.4331,
   "toLat": 55.5015,
   "toLon": -4.5772,
   "distance": 23,
   "runway": 9800,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 03m"
  },
  {
   "id": 8,
   "from": "EGPK",
   "fromName": "Glasgow Prestwick Airport",
   "to": "EGPH",
   "toName": "Edinburgh Airport",
   "fromLat": 55.5015,
   "fromLon": -4.5772,
   "toLat": 55.9501,
   "toLon": -3.3723,
   "distance": 49,
   "runway": 8392,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 07m"
  },
  {
   "id": 9,
   "from": "EGPH",
   "fromName": "Edinburgh Airport",
   "to": "EGPN",
   "toName": "Dundee Airport",
   "fromLat": 55.9501,
   "fromLon": -3.3723,
   "toLat": 56.4525,
   "toLon": -3.0258,
   "distance": 32,
   "runway": 4593,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "Regional (ATR/ERJ)",
   "speed": 270,
   "flightTime": "0h 07m"
  },
  {
   "id": 10,
   "from": "EGPN",
   "fromName": "Dundee Airport",
   "to": "EGPH",
   "toName": "Edinburgh Airport",
   "fromLat": 56.4525,
   "fromLon": -3.0258,
   "toLat": 55.9501,
   "toLon": -3.3723,
   "distance": 32,
   "runway": 8392,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 04m"
  },
  {
   "id": 11,
   "from": "EGPH",
   "fromName": "Edinburgh Airport",
   "to": "EGPN",
   "toName": "Dundee Airport",
   "fromLat": 55.9501,
   "fromLon": -3.3723,
   "toLat": 56.4525,
   "toLon": -3.0258,
   "distance": 32,
   "runway": 4593,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "Regional (ATR/ERJ)",
   "speed": 270,
   "flightTime": "0h 07m"
  },
  {
   "id": 12,
   "from": "EGPN",
   "fromName": "Dundee Airport",
   "to": "EGPH",
   "toName": "Edinburgh Airport",
   "fromLat": 56.4525,
   "fromLon": -3.0258,
   "toLat": 55.9501,
   "toLon": -3.3723,
   "distance": 32,
   "runway": 8392,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 04m"
  },
  {
   "id": 13,
   "from": "EGPH",
   "fromName": "Edinburgh Airport",
   "to": "EGPN",
   "toName": "Dundee Airport",
   "fromLat": 55.9501,
   "fromLon": -3.3723,
   "toLat": 56.4525,
   "toLon": -3.0258,
   "distance": 32,
   "runway": 4593,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "Regional (ATR/ERJ)",
   "speed": 270,
   "flightTime": "0h 07m"
  },
  {
   "id": 14,
   "from": "EGPN",
   "fromName": "Dundee Airport",
   "to": "EIKY",
   "toName": "Kerry Airport",
   "fromLat": 56.4525,
   "fromLon": -3.0258,
   "toLat": 52.1809,
   "toLon": -9.5238,
   "distance": 343,
   "runway": 6562,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 46m"
  },
  {
   "id": 15,
   "from": "EIKY",
   "fromName": "Kerry Airport",
   "to": "EIDW",
   "toName": "Dublin Airport",
   "fromLat": 52.1809,
   "fromLon": -9.5238,
   "toLat": 53.4287,
   "toLon": -6.2621,
   "distance": 140,
   "runway": 10203,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 19m"
  },
  {
   "id": 16,
   "from": "EIDW",
   "fromName": "Dublin Airport",
   "to": "EINN",
   "toName": "Shannon Airport",
   "fromLat": 53.4287,
   "fromLon": -6.2621,
   "toLat": 52.702,
   "toLon": -8.9248,
   "distance": 106,
   "runway": 10495,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 14m"
  },
  {
   "id": 17,
   "from": "EINN",
   "fromName": "Shannon Airport",
   "to": "ESMS",
   "toName": "Malmö Sturup Airport",
   "fromLat": 52.702,
   "fromLon": -8.9248,
   "toLat": 55.5356,
   "toLon": 13.3763,
   "distance": 799,
   "runway": 9186,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 47m"
  },
  {
   "id": 18,
   "from": "ESMS",
   "fromName": "Malmö Sturup Airport",
   "to": "ENEV",
   "toName": "Harstad/Narvik Airport",
   "fromLat": 55.5356,
   "fromLon": 13.3763,
   "toLat": 68.4913,
   "toLon": 16.6781,
   "distance": 783,
   "runway": 9236,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 44m"
  },
  {
   "id": 19,
   "from": "ENEV",
   "fromName": "Harstad/Narvik Airport",
   "to": "ENLK",
   "toName": "Leknes Airport",
   "fromLat": 68.4913,
   "fromLon": 16.6781,
   "toLat": 68.1525,
   "toLon": 13.6094,
   "distance": 71,
   "runway": 2881,
   "gaOk": true,
   "regionalOk": false,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "speed": 200,
   "flightTime": "0h 21m"
  },
  {
   "id": 20,
   "from": "ENLK",
   "fromName": "Leknes Airport",
   "to": "ESMT",
   "toName": "Halmstad Airport",
   "fromLat": 68.1525,
   "fromLon": 13.6094,
   "toLat": 56.6911,
   "toLon": 12.8202,
   "distance": 688,
   "runway": 7419,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 32m"
  },
  {
   "id": 21,
   "from": "ESMT",
   "fromName": "Halmstad Airport",
   "to": "ESSB",
   "toName": "Stockholm-Bromma Airport",
   "fromLat": 56.6911,
   "fromLon": 12.8202,
   "toLat": 59.3544,
   "toLon": 17.9417,
   "distance": 228,
   "runway": 5472,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 30m"
  },
  {
   "id": 22,
   "from": "ESSB",
   "fromName": "Stockholm-Bromma Airport",
   "to": "ESSV",
   "toName": "Visby Airport",
   "fromLat": 59.3544,
   "fromLon": 17.9417,
   "toLat": 57.6628,
   "toLon": 18.3462,
   "distance": 102,
   "runway": 6562,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 14m"
  },
  {
   "id": 23,
   "from": "ESSV",
   "fromName": "Visby Airport",
   "to": "LEGE",
   "toName": "Girona-Costa Brava Airport",
   "fromLat": 57.6628,
   "fromLon": 18.3462,
   "toLat": 41.9046,
   "toLon": 2.7618,
   "distance": 1117,
   "runway": 7874,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "2h 29m"
  },
  {
   "id": 24,
   "from": "LEGE",
   "fromName": "Girona-Costa Brava Airport",
   "to": "LEMG",
   "toName": "Málaga-Costa del Sol Airport",
   "fromLat": 41.9046,
   "fromLon": 2.7618,
   "toLat": 36.6749,
   "toLon": -4.4991,
   "distance": 461,
   "runway": 10500,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 01m"
  },
  {
   "id": 25,
   "from": "LEMG",
   "fromName": "Málaga-Costa del Sol Airport",
   "to": "LIRF",
   "toName": "Rome–Fiumicino Leonardo da Vinci International Airport",
   "fromLat": 36.6749,
   "fromLon": -4.4991,
   "toLat": 41.8045,
   "toLon": 12.252,
   "distance": 836,
   "runway": 12801,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 51m"
  },
  {
   "id": 26,
   "from": "LIRF",
   "fromName": "Rome–Fiumicino Leonardo da Vinci International Airport",
   "to": "LPFR",
   "toName": "Faro - Gago Coutinho International Airport",
   "fromLat": 41.8045,
   "fromLon": 12.252,
   "toLat": 37.0159,
   "toLon": -7.9709,
   "distance": 978,
   "runway": 8169,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "2h 10m"
  },
  {
   "id": 27,
   "from": "LPFR",
   "fromName": "Faro - Gago Coutinho International Airport",
   "to": "LPPT",
   "toName": "Lisbon Humberto Delgado Airport",
   "fromLat": 37.0159,
   "fromLon": -7.9709,
   "toLat": 38.7813,
   "toLon": -9.1359,
   "distance": 120,
   "runway": 12500,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 16m"
  },
  {
   "id": 28,
   "from": "LPPT",
   "fromName": "Lisbon Humberto Delgado Airport",
   "to": "FACT",
   "toName": "Cape Town International Airport",
   "fromLat": 38.7813,
   "fromLon": -9.1359,
   "toLat": -33.974,
   "toLon": 18.6043,
   "distance": 4633,
   "runway": 10502,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Widebody (A340/A350/777/MD-11)",
   "speed": 480,
   "flightTime": "9h 39m"
  },
  {
   "id": 29,
   "from": "FACT",
   "fromName": "Cape Town International Airport",
   "to": "FAGG",
   "toName": "George Airport",
   "fromLat": -33.974,
   "fromLon": 18.6043,
   "toLat": -34.0056,
   "toLon": 22.3789,
   "distance": 188,
   "runway": 6562,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 25m"
  },
  {
   "id": 30,
   "from": "FAGG",
   "fromName": "George Airport",
   "to": "FAOR",
   "toName": "O.R. Tambo International Airport",
   "fromLat": -34.0056,
   "fromLon": 22.3789,
   "toLat": -26.1401,
   "toLon": 28.2468,
   "distance": 562,
   "runway": 14495,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 15m"
  },
  {
   "id": 31,
   "from": "FAOR",
   "fromName": "O.R. Tambo International Airport",
   "to": "FANS",
   "toName": "Nelspruit Airport",
   "fromLat": -26.1401,
   "fromLon": 28.2468,
   "toLat": -25.5,
   "toLon": 30.9138,
   "distance": 149,
   "runway": 3419,
   "gaOk": true,
   "regionalOk": false,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "speed": 200,
   "flightTime": "0h 45m"
  },
  {
   "id": 32,
   "from": "FANS",
   "fromName": "Nelspruit Airport",
   "to": "FAPN",
   "toName": "Pilanesberg International Airport",
   "fromLat": -25.5,
   "fromLon": 30.9138,
   "toLat": -25.3338,
   "toLon": 27.1734,
   "distance": 203,
   "runway": 9022,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 27m"
  },
  {
   "id": 33,
   "from": "FAPN",
   "fromName": "Pilanesberg International Airport",
   "to": "OMAA",
   "toName": "Zayed International Airport",
   "fromLat": -25.3338,
   "fromLon": 27.1734,
   "toLat": 24.441,
   "toLon": 54.6492,
   "distance": 3388,
   "runway": 13471,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Widebody (A340/A350/777/MD-11)",
   "speed": 480,
   "flightTime": "7h 04m"
  },
  {
   "id": 34,
   "from": "OMAA",
   "fromName": "Zayed International Airport",
   "to": "OMDB",
   "toName": "Dubai International Airport",
   "fromLat": 24.441,
   "fromLon": 54.6492,
   "toLat": 25.2498,
   "toLon": 55.371,
   "distance": 62,
   "runway": 14590,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 08m"
  },
  {
   "id": 35,
   "from": "OMDB",
   "fromName": "Dubai International Airport",
   "to": "RJBB",
   "toName": "Kansai International Airport",
   "fromLat": 25.2498,
   "fromLon": 55.371,
   "toLat": 34.4273,
   "toLon": 135.244,
   "distance": 4091,
   "runway": 13123,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Widebody (A340/A350/777/MD-11)",
   "speed": 480,
   "flightTime": "8h 31m"
  },
  {
   "id": 36,
   "from": "RJBB",
   "fromName": "Kansai International Airport",
   "to": "RJTT",
   "toName": "Tokyo Haneda International Airport",
   "fromLat": 34.4273,
   "fromLon": 135.244,
   "toLat": 35.5497,
   "toLon": 139.787,
   "distance": 233,
   "runway": 11024,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 31m"
  },
  {
   "id": 37,
   "from": "RJTT",
   "fromName": "Tokyo Haneda International Airport",
   "to": "RJTO",
   "toName": "Oshima Airport",
   "fromLat": 35.5497,
   "fromLon": 139.787,
   "toLat": 34.782,
   "toLon": 139.36,
   "distance": 51,
   "runway": 5905,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "speed": 200,
   "flightTime": "0h 15m"
  },
  {
   "id": 38,
   "from": "RJTO",
   "fromName": "Oshima Airport",
   "to": "RKPC",
   "toName": "Jeju International Airport",
   "fromLat": 34.782,
   "fromLon": 139.36,
   "toLat": 33.5121,
   "toLon": 126.4925,
   "distance": 643,
   "runway": 10433,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 26m"
  },
  {
   "id": 39,
   "from": "RKPC",
   "fromName": "Jeju International Airport",
   "to": "WSSS",
   "toName": "Singapore Changi Airport",
   "fromLat": 33.5121,
   "fromLon": 126.4925,
   "toLat": 1.3502,
   "toLon": 103.994,
   "distance": 2309,
   "runway": 13123,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "5h 08m"
  },
  {
   "id": 40,
   "from": "WSSS",
   "fromName": "Singapore Changi Airport",
   "to": "ZGSZ",
   "toName": "Shenzhen Bao'an International Airport",
   "fromLat": 1.3502,
   "fromLon": 103.994,
   "toLat": 22.6395,
   "toLon": 113.8033,
   "distance": 1400,
   "runway": 12467,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "3h 07m"
  },
  {
   "id": 41,
   "from": "ZGSZ",
   "fromName": "Shenzhen Bao'an International Airport",
   "to": "NZAA",
   "toName": "Auckland International Airport",
   "fromLat": 22.6395,
   "fromLon": 113.8033,
   "toLat": -37.012,
   "toLon": 174.7863,
   "distance": 4970,
   "runway": 11926,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Widebody (A340/A350/777/MD-11)",
   "speed": 480,
   "flightTime": "10h 21m"
  },
  {
   "id": 42,
   "from": "NZAA",
   "fromName": "Auckland International Airport",
   "to": "NZKK",
   "toName": "Kerikeri Airport",
   "fromLat": -37.012,
   "fromLon": 174.7863,
   "toLat": -35.2591,
   "toLon": 173.9133,
   "distance": 113,
   "runway": 3904,
   "gaOk": true,
   "regionalOk": false,
   "narrowbodyOk": false,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "speed": 200,
   "flightTime": "0h 34m"
  },
  {
   "id": 43,
   "from": "NZKK",
   "fromName": "Kerikeri Airport",
   "to": "NZNR",
   "toName": "Hawke's Bay Airport",
   "fromLat": -35.2591,
   "fromLon": 173.9133,
   "toLat": -39.4658,
   "toLon": 176.87,
   "distance": 289,
   "runway": 5741,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 39m"
  },
  {
   "id": 44,
   "from": "NZNR",
   "fromName": "Hawke's Bay Airport",
   "to": "NZQN",
   "toName": "Queenstown Airport",
   "fromLat": -39.4658,
   "fromLon": 176.87,
   "toLat": -45.0192,
   "toLon": 168.7464,
   "distance": 491,
   "runway": 6204,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 05m"
  },
  {
   "id": 45,
   "from": "NZQN",
   "fromName": "Queenstown Airport",
   "to": "YMML",
   "toName": "Melbourne Airport",
   "fromLat": -45.0192,
   "fromLon": 168.7464,
   "toLat": -37.6707,
   "toLon": 144.8379,
   "distance": 1159,
   "runway": 11998,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "2h 35m"
  },
  {
   "id": 46,
   "from": "YMML",
   "fromName": "Melbourne Airport",
   "to": "YDPO",
   "toName": "Devonport Airport",
   "fromLat": -37.6707,
   "fromLon": 144.8379,
   "toLat": -41.1697,
   "toLon": 146.43,
   "distance": 223,
   "runway": 6030,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 30m"
  },
  {
   "id": 47,
   "from": "YDPO",
   "fromName": "Devonport Airport",
   "to": "YMML",
   "toName": "Melbourne Airport",
   "fromLat": -41.1697,
   "fromLon": 146.43,
   "toLat": -37.6707,
   "toLon": 144.8379,
   "distance": 223,
   "runway": 11998,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 30m"
  },
  {
   "id": 48,
   "from": "YMML",
   "fromName": "Melbourne Airport",
   "to": "YKII",
   "toName": "King Island Airport",
   "fromLat": -37.6707,
   "fromLon": 144.8379,
   "toLat": -39.8775,
   "toLon": 143.878,
   "distance": 140,
   "runway": 5198,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "GA / Light Jet",
   "speed": 200,
   "flightTime": "0h 42m"
  },
  {
   "id": 49,
   "from": "YKII",
   "fromName": "King Island Airport",
   "to": "PHOG",
   "toName": "Kahului International Airport",
   "fromLat": -39.8775,
   "fromLon": 143.878,
   "toLat": 20.8963,
   "toLon": -156.4318,
   "distance": 4944,
   "runway": 6998,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Widebody (A340/A350/777/MD-11)",
   "speed": 480,
   "flightTime": "10h 18m"
  },
  {
   "id": 50,
   "from": "PHOG",
   "fromName": "Kahului International Airport",
   "to": "CYQY",
   "toName": "Sydney / J.A. Douglas McCurdy Airport",
   "fromLat": 20.8963,
   "fromLon": -156.4318,
   "toLat": 46.1611,
   "toLon": -60.0498,
   "distance": 4762,
   "runway": 7070,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Widebody (A340/A350/777/MD-11)",
   "speed": 480,
   "flightTime": "9h 55m"
  },
  {
   "id": 51,
   "from": "CYQY",
   "fromName": "Sydney / J.A. Douglas McCurdy Airport",
   "to": "KAGS",
   "toName": "Augusta Regional At Bush Field",
   "fromLat": 46.1611,
   "fromLon": -60.0498,
   "toLat": 33.3699,
   "toLon": -81.9645,
   "distance": 1263,
   "runway": 8001,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "2h 48m"
  },
  {
   "id": 52,
   "from": "KAGS",
   "fromName": "Augusta Regional At Bush Field",
   "to": "KCHS",
   "toName": "Charleston International Airport",
   "fromLat": 33.3699,
   "fromLon": -81.9645,
   "toLat": 32.8962,
   "toLon": -80.0382,
   "distance": 101,
   "runway": 9001,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 13m"
  },
  {
   "id": 53,
   "from": "KCHS",
   "fromName": "Charleston International Airport",
   "to": "KSOP",
   "toName": "Moore County Airport",
   "fromLat": 32.8962,
   "fromLon": -80.0382,
   "toLat": 35.2372,
   "toLon": -79.3894,
   "distance": 144,
   "runway": 6503,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 19m"
  },
  {
   "id": 54,
   "from": "KSOP",
   "fromName": "Moore County Airport",
   "to": "KAIA",
   "toName": "Alliance Municipal Airport",
   "fromLat": 35.2372,
   "fromLon": -79.3894,
   "toLat": 42.0525,
   "toLon": -102.804,
   "distance": 1167,
   "runway": 9203,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "2h 36m"
  },
  {
   "id": 55,
   "from": "KAIA",
   "fromName": "Alliance Municipal Airport",
   "to": "KJAX",
   "toName": "Jacksonville International Airport",
   "fromLat": 42.0525,
   "fromLon": -102.804,
   "toLat": 30.4925,
   "toLon": -81.6878,
   "distance": 1230,
   "runway": 10000,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "2h 44m"
  },
  {
   "id": 56,
   "from": "KJAX",
   "fromName": "Jacksonville International Airport",
   "to": "KSBM",
   "toName": "Sheboygan County Memorial Airport",
   "fromLat": 30.4925,
   "fromLon": -81.6878,
   "toLat": 43.7696,
   "toLon": -87.8514,
   "distance": 849,
   "runway": 6801,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 53m"
  },
  {
   "id": 57,
   "from": "KSBM",
   "fromName": "Sheboygan County Memorial Airport",
   "to": "KOTH",
   "toName": "Southwest Oregon Regional Airport",
   "fromLat": 43.7696,
   "fromLon": -87.8514,
   "toLat": 43.4171,
   "toLon": -124.246,
   "distance": 1570,
   "runway": 5980,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "3h 29m"
  },
  {
   "id": 58,
   "from": "KOTH",
   "fromName": "Southwest Oregon Regional Airport",
   "to": "KSEA",
   "toName": "Seattle–Tacoma International Airport",
   "fromLat": 43.4171,
   "fromLon": -124.246,
   "toLat": 47.4479,
   "toLon": -122.3103,
   "distance": 255,
   "runway": 11901,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 34m"
  },
  {
   "id": 59,
   "from": "KSEA",
   "fromName": "Seattle–Tacoma International Airport",
   "to": "KMRY",
   "toName": "Monterey Regional Airport",
   "fromLat": 47.4479,
   "fromLon": -122.3103,
   "toLat": 36.5868,
   "toLon": -121.8442,
   "distance": 652,
   "runway": 7175,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 27m"
  },
  {
   "id": 60,
   "from": "KMRY",
   "fromName": "Monterey Regional Airport",
   "to": "SAEZ",
   "toName": "Ezeiza International Airport - Ministro Pistarini",
   "fromLat": 36.5868,
   "fromLon": -121.8442,
   "toLat": -34.8222,
   "toLon": -58.5358,
   "distance": 5556,
   "runway": 10827,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Widebody (A340/A350/777/MD-11)",
   "speed": 480,
   "flightTime": "11h 34m"
  },
  {
   "id": 61,
   "from": "SAEZ",
   "fromName": "Ezeiza International Airport - Ministro Pistarini",
   "to": "SAZY",
   "toName": "Aviador C. Campos Airport",
   "fromLat": -34.8222,
   "fromLon": -58.5358,
   "toLat": -40.0754,
   "toLon": -71.1373,
   "distance": 678,
   "runway": 8205,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": false,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "1h 30m"
  },
  {
   "id": 62,
   "from": "SAZY",
   "fromName": "Aviador C. Campos Airport",
   "to": "SBGL",
   "toName": "Rio Galeão – Tom Jobim International Airport",
   "fromLat": -40.0754,
   "fromLon": -71.1373,
   "toLat": -22.81,
   "toLon": -43.2506,
   "distance": 1752,
   "runway": 13123,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "3h 54m"
  },
  {
   "id": 63,
   "from": "SBGL",
   "fromName": "Rio Galeão – Tom Jobim International Airport",
   "to": "SBGR",
   "toName": "São Paulo/Guarulhos–Governor André Franco Montoro International Airport",
   "fromLat": -22.81,
   "fromLon": -43.2506,
   "toLat": -23.4313,
   "toLon": -46.47,
   "distance": 182,
   "runway": 12139,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Narrowbody (A320/737)",
   "speed": 450,
   "flightTime": "0h 24m"
  },
  {
   "id": 64,
   "from": "SBGR",
   "fromName": "São Paulo/Guarulhos–Governor André Franco Montoro International Airport",
   "to": "EGAA",
   "toName": "Belfast International Airport",
   "fromLat": -23.4313,
   "fromLon": -46.47,
   "toLat": 54.6575,
   "toLon": -6.2158,
   "distance": 5126,
   "runway": 9121,
   "gaOk": true,
   "regionalOk": true,
   "narrowbodyOk": true,
   "widebodyOk": true,
   "category": "Widebody (A340/A350/777/MD-11)",
   "speed": 480,
   "flightTime": "10h 41m"
  }
 ],
 "airports": {
  "EGAA": [
   54.6575,
   -6.2158
  ],
  "EGAE": [
   55.0428,
   -7.1611
  ],
  "EGCC": [
   53.3494,
   -2.2795
  ],
  "EGKK": [
   51.1487,
   -0.1857
  ],
  "EGLF": [
   51.2758,
   -0.7763
  ],
  "EGPE": [
   57.5425,
   -4.0475
  ],
  "EGPF": [
   55.8719,
   -4.4331
  ],
  "EGPK": [
   55.5015,
   -4.5772
  ],
  "EGPH": [
   55.9501,
   -3.3723
  ],
  "EGPN": [
   56.4525,
   -3.0258
  ],
  "EIKY": [
   52.1809,
   -9.5238
  ],
  "EIDW": [
   53.4287,
   -6.2621
  ],
  "EINN": [
   52.702,
   -8.9248
  ],
  "ESMS": [
   55.5356,
   13.3763
  ],
  "ENEV": [
   68.4913,
   16.6781
  ],
  "ENLK": [
   68.1525,
   13.6094
  ],
  "ESMT": [
   56.6911,
   12.8202
  ],
  "ESSB": [
   59.3544,
   17.9417
  ],
  "ESSV": [
   57.6628,
   18.3462
  ],
  "LEGE": [
   41.9046,
   2.7618
  ],
  "LEMG": [
   36.6749,
   -4.4991
  ],
  "LIRF": [
   41.8045,
   12.252
  ],
  "LPFR": [
   37.0159,
   -7.9709
  ],
  "LPPT": [
   38.7813,
   -9.1359
  ],
  "FACT": [
   -33.974,
   18.6043
  ],
  "FAGG": [
   -34.0056,
   22.3789
  ],
  "FAOR": [
   -26.1401,
   28.2468
  ],
  "FANS": [
   -25.5,
   30.9138
  ],
  "FAPN": [
   -25.3338,
   27.1734
  ],
  "OMAA": [
   24.441,
   54.6492
  ],
  "OMDB": [
   25.2498,
   55.371
  ],
  "RJBB": [
   34.4273,
   135.244
  ],
  "RJTT": [
   35.5497,
   139.787
  ],
  "RJTO": [
   34.782,
   139.36
  ],
  "RKPC": [
   33.5121,
   126.4925
  ],
  "WSSS": [
   1.3502,
   103.994
  ],
  "ZGSZ": [
   22.6395,
   113.8033
  ],
  "NZAA": [
   -37.012,
   174.7863
  ],
  "NZKK": [
   -35.2591,
   173.9133
  ],
  "NZNR": [
   -39.4658,
   176.87
  ],
  "NZQN": [
   -45.0192,
   168.7464
  ],
  "YMML": [
   -37.6707,
   144.8379
  ],
  "YDPO": [
   -41.1697,
   146.43
  ],
  "YKII": [
   -39.8775,
   143.878
  ],
  "PHOG": [
   20.8963,
   -156.4318
  ],
  "CYQY": [
   46.1611,
   -60.0498
  ],
  "KAGS": [
   33.3699,
   -81.9645
  ],
  "KCHS": [
   32.8962,
   -80.0382
  ],
  "KSOP": [
   35.2372,
   -79.3894
  ],
  "KAIA": [
   42.0525,
   -102.804
  ],
  "KJAX": [
   30.4925,
   -81.6878
  ],
  "KSBM": [
   43.7696,
   -87.8514
  ],
  "KOTH": [
   43.4171,
   -124.246
  ],
  "KSEA": [
   47.4479,
   -122.3103
  ],
  "KMRY": [
   36.5868,
   -121.8442
  ],
  "SAEZ": [
   -34.8222,
   -58.5358
  ],
  "SAZY": [
   -40.0754,
   -71.1373
  ],
  "SBGL": [
   -22.81,
   -43.2506
  ],
  "SBGR": [
   -23.4313,
   -46.47
  ]
 },
 "regions": [
  "Europe",
  "Africa",
  "Asia",
  "Oceania",
  "Pacific",
  "North America",
  "South America"
 ],
 "stats": {
  "played": "0 / 66",
  "completion": 0,
  "totalLegs": 64,
  "distanceNm": 63664,
  "flightTimeH": 137.869166666667,
  "distanceKm": 117905.728
 },
 "legsByCategory": {
  "GA / Light Jet": 5,
  "Regional (ATR/ERJ)": 3,
  "Narrowbody (A320/737)": 48,
  "Widebody (A340/A350/777/MD-11)": 8
 },
 "missing": []
};
